routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('bienvenido',function(){
// 	return "bienvenidos";
// });
Route::resource('ticket', 'Prueba1Controller');

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    protected $fillable = ['codigo','nivel','fecha']; 
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Prueba1Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Ticket;

class Prueba1Controller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Vticket = Ticket::all();
        return view('tickets.index',compact('Vticket'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tickets.newticktes');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $ticket = new Ticket;
        $ticket->codigo = $request->input('codigo');
        $ticket->nivel = $request->input('Nimportancia');
        $ticket->fecha = $request->input('fecha');
        $ticket->save();
        return redirect()->route('ticket.index')->with('info', 'Hemos recibido tu mensaje');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $Vticket = Ticket::findOrfail($id);
        return view('tickets.edit', compact('Vticket'));
        // return "dentro de show".$Vticket ;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Vticket = Ticket::findOrfail($id);
        return view('tickets.edit', compact('Vticket'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Vticket = Ticket::findOrfail($id);
        // return $request;
        $Vticket->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // return "el valor del id ".$id;
        Ticket::findOrfail($id)->delete();
        return redirect()->route('ticket.index');
    }
}

resources/views/layout.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Laravel</title>
  </head>
  <body>
    <h1>Practica de Laravel</h1>
    <section>
      <div class="container">
        @yield('seccion')
      </div>
    </section>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/tickets/edit.blade.php
@extends('layout')
@section('seccion')
<h2>Tickets Nro: {{ $Vticket->id }}</h2>
	<form method="POST" action="{{ route('ticket.update', $Vticket->id) }}">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="PUT">
        {{-- @csrf --}}
		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="codigo">Codigo</label>
				<input type="text" class="form-control" id="codigo" name = "codigo" placeholder="Codigo" value = "{{ $Vticket->codigo }}">
			</div>
		</div>
		<div class="form-row ">
            <div class="form-group col-md-6">
                <label for="NImportancia">Nivel de importancia</label>
                <input type="text" class="form-control" name = "Nimportancia" id="Nimportancia" placeholder="Nivel de Importancia" value = "{{ $Vticket->nivel }}">
            </div>
		</div>
		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="fecha">Fecha </label>
				<input type="text" class="form-control" id="fecha" name="fecha" value = "{{ $Vticket->fecha }}">
			</div>
		</div>

		<button type="submit" class="btn btn-primary">Guardar</button>
	</form>
@endsection

resources/views/tickets/index.blade.php
@extends('layout')
@section('seccion')

<div>
	<table class="table">
			{!! csrf_field() !!}
			{!! method_field('DELETE') !!}
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Codigo</th>
				<th scope="col">Nivel</th>
				<th scope="col">Fecha</th>
				<th><a class="btn btn-primary" href="{{ route('ticket.create') }}" role="button">Nuevo Ticket</a></th>
			</tr>
		</thead>
		<tbody>
			@foreach($Vticket as $tickets)
				<tr>
					<th scope="row">{{$tickets->id}}</th>
					<th >{{$tickets->codigo}}</th>
					<th >{{$tickets->nivel}}</th>
					<th >{{$tickets->fecha}}</th>
					<th><a class="btn btn-success" href="{{ route('ticket.edit', $tickets->id) }}" role="button">Modificar</a></th>
					<th>
						<form method = "POST" action="{{ route('ticket.destroy', $tickets->id) }}">
							@csrf
							@method('DELETE')
							
							<button class="btn btn-danger" type="submit">Eliminar</button>
						</form>
					</th>
				</tr>
			@endforeach
		</tbody>
	</table>
</div>

@endsection

resources/views/tickets/newticktes.blade.php
@extends('layout')
@section('seccion')
	<h2>Creación de los tickets</h2>
	<form method="POST" action="{{ route('ticket.store') }}">
		@csrf
		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="codigo">Codigo</label>
				<input type="text" class="form-control" id="codigo" name = "codigo" placeholder="Codigo">
			</div>
		</div>
		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="NImportancia">Nivel de importancia</label>
				<input type="text" class="form-control" name = "Nimportancia" id="Nimportancia" placeholder="Nivel de Importancia">
			</div>
		</div>
		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="fecha">Fecha </label>
				<input type="text" class="form-control" id="fecha" name="fecha">
			</div>
		</div>

		<button type="submit" class="btn btn-primary">Guardar</button>
	</form>
@endsection